In [1]:
# ===================================================================
# ⚙️ 1. SETUP AND CONFIGURATION
# ===================================================================
# Import libraries, define paths, and load configuration files.
# ===================================================================
import pandas as pd
from pathlib import Path
import yaml
import logging

# Import our custom gaitlab modules
from gaitlab.utils import discover_subjects
from gaitlab.core import Trial
from gaitlab.analysis import (
    generate_coverage_report,
    calculate_normative_stats,
    calculate_spatiotemporal_stats,
    generate_kinetic_qc_report
)
from gaitlab.plotting import PngPlotter, HtmlPlotter

# --- Configuration Paths ---
# ⚠️ ACTION: Update these paths to match your system.
BASE_DIR = Path(r"C:/Users/fx517/Documents/codigo/results/EUROBENCH_RESULTS/c3d_CES/VICON")
OUTPUT_DIR = Path("./output")
CONFIG_DIR = Path("./config")

# --- Directory and Logging Setup ---
subfolders = ["figures", "tables", "logs", "html"]
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
for sf in subfolders:
    (OUTPUT_DIR / sf).mkdir(exist_ok=True)

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler(OUTPUT_DIR / "logs" / "pipeline_notebook.log", mode='w', encoding='utf-8'),
        logging.StreamHandler()
    ]
)

# --- Load Configuration Files ---
try:
    with open(CONFIG_DIR / "variables_map.yaml", "r") as f:
        VARS_MAP = yaml.safe_load(f)
    with open(CONFIG_DIR / "plot_layout.yaml", "r") as f:
        LAYOUT_CONFIG = yaml.safe_load(f)
    logging.info("Configuration files loaded successfully.")
except FileNotFoundError as e:
    logging.error(f"Configuration file not found: {e}.")
    VARS_MAP, LAYOUT_CONFIG = {}, {}

2026-07-02 15:32:32,083 - INFO - Configuration files loaded successfully.

In [2]:
# ===================================================================
# 🚀 2. PIPELINE EXECUTION
# ===================================================================
# Discover subjects and process each trial in a loop.
# ===================================================================
logging.info("--- Starting Pipeline Execution ---")

subjects_list, files_by_subject = discover_subjects(BASE_DIR)
logging.info(f"Discovered {len(subjects_list)} subjects.")

all_timeseries = []
all_spatiotemporal = []
kinetic_qc_records = []

for subject_id in subjects_list:
    try:
        trial = Trial(subject_id, files_by_subject[subject_id], VARS_MAP)
        if trial.is_valid:
            timeseries_data = trial.process_time_series()
            if timeseries_data is not None:
                all_timeseries.append(timeseries_data)

            if trial.spatiotemporal_params:
                all_spatiotemporal.extend(trial.spatiotemporal_params)

            for side, valid in trial.kinetic_valid.items():
                kinetic_qc_records.append((subject_id, side, valid))
    except Exception as e:
        logging.error(f"Critical error processing {subject_id}: {e}", exc_info=True)

# --- Consolidate Results ---
if all_timeseries:
    master_df = pd.concat(all_timeseries, ignore_index=True)
    spatiotemporal_df = pd.DataFrame(all_spatiotemporal)
    logging.info(f"Successfully processed data for {master_df['subject_id'].nunique()} subjects.")
    print("--- Master DataFrame Preview ---")
    display(master_df.head())
else:
    logging.warning("Pipeline finished, but no data was processed.")
    master_df, spatiotemporal_df = pd.DataFrame(), pd.DataFrame()

2026-07-02 15:32:32,090 - INFO - --- Starting Pipeline Execution ---

2026-07-02 15:32:32,143 - INFO - Discovered 181 subjects.

2026-07-02 15:32:32,186 - WARNING - subject_002: kinetic data flagged invalid on left (peak |forces.ankle.z.left|=nan < threshold=0.5)

2026-07-02 15:32:32,187 - WARNING - subject_002: kinetic data flagged invalid on right (peak |forces.ankle.z.right|=nan < threshold=0.5)

2026-07-02 15:32:32,334 - WARNING - subject_005: kinetic data flagged invalid on left (peak |forces.ankle.z.left|=nan < threshold=0.5)

2026-07-02 15:32:32,338 - WARNING - subject_005: kinetic data flagged invalid on right (peak |forces.ankle.z.right|=nan < threshold=0.5)

2026-07-02 15:32:32,533 - WARNING - subject_009: kinetic data flagged invalid on left (peak |forces.ankle.z.left|=0.1370548189518187 < threshold=0.5)

2026-07-02 15:32:32,533 - WARNING - subject_009: kinetic data flagged invalid on right (peak |forces.ankle.z.right|=0.1146781395676316 < threshold=0.5)

2026-07-02 15:32:32,750 - WARNING - subject_013: kinetic data flagged invalid on left (peak |forces.ankle.z.left|=nan < threshold=0.5)

2026-07-02 15:32:32,751 - WARNING - subject_013: kinetic data flagged invalid on right (peak |forces.ankle.z.right|=0.3578628679632292 < threshold=0.5)

2026-07-02 15:32:33,186 - WARNING - subject_022: kinetic data flagged invalid on left (peak |forces.ankle.z.left|=0.040721756385008 < threshold=0.5)

2026-07-02 15:32:33,187 - WARNING - subject_022: kinetic data flagged invalid on right (peak |forces.ankle.z.right|=0.0898924490040343 < threshold=0.5)

2026-07-02 15:32:33,804 - WARNING - subject_035: kinetic data flagged invalid on left (peak |forces.ankle.z.left|=0.2030399189078789 < threshold=0.5)

2026-07-02 15:32:33,804 - WARNING - subject_035: kinetic data flagged invalid on right (peak |forces.ankle.z.right|=0.0557493617180592 < threshold=0.5)

2026-07-02 15:32:34,139 - WARNING - subject_042: kinetic data flagged invalid on left (peak |forces.ankle.z.left|=0.1685827710162722 < threshold=0.5)

2026-07-02 15:32:34,140 - WARNING - subject_042: kinetic data flagged invalid on right (peak |forces.ankle.z.right|=nan < threshold=0.5)

2026-07-02 15:32:34,385 - WARNING - subject_047: kinetic data flagged invalid on left (peak |forces.ankle.z.left|=0.2149327147364478 < threshold=0.5)

2026-07-02 15:32:34,386 - WARNING - subject_047: kinetic data flagged invalid on right (peak |forces.ankle.z.right|=0.1054676645726188 < threshold=0.5)

2026-07-02 15:32:35,150 - WARNING - subject_063: kinetic data flagged invalid on left (peak |forces.ankle.z.left|=0.1258190451372946 < threshold=0.5)

2026-07-02 15:32:35,150 - WARNING - subject_063: kinetic data flagged invalid on right (peak |forces.ankle.z.right|=0.1318079560654153 < threshold=0.5)

2026-07-02 15:32:35,491 - WARNING - subject_071: kinetic data flagged invalid on left (peak |forces.ankle.z.left|=nan < threshold=0.5)

2026-07-02 15:32:35,492 - WARNING - subject_071: kinetic data flagged invalid on right (peak |forces.ankle.z.right|=nan < threshold=0.5)

2026-07-02 15:32:35,887 - WARNING - subject_080: kinetic data flagged invalid on left (peak |forces.ankle.z.left|=0.2889310782163831 < threshold=0.5)

2026-07-02 15:32:35,887 - WARNING - subject_080: kinetic data flagged invalid on right (peak |forces.ankle.z.right|=0.132912281146175 < threshold=0.5)

2026-07-02 15:32:36,450 - WARNING - subject_092: kinetic data flagged invalid on left (peak |forces.ankle.z.left|=nan < threshold=0.5)

2026-07-02 15:32:36,451 - WARNING - subject_092: kinetic data flagged invalid on right (peak |forces.ankle.z.right|=nan < threshold=0.5)

2026-07-02 15:32:36,677 - WARNING - subject_097: kinetic data flagged invalid on left (peak |forces.ankle.z.left|=0.1324510752957554 < threshold=0.5)

2026-07-02 15:32:36,677 - WARNING - subject_097: kinetic data flagged invalid on right (peak |forces.ankle.z.right|=0.0906574746368261 < threshold=0.5)

2026-07-02 15:32:37,416 - WARNING - subject_113: kinetic data flagged invalid on left (peak |forces.ankle.z.left|=0.0716763750838423 < threshold=0.5)

2026-07-02 15:32:37,417 - WARNING - subject_113: kinetic data flagged invalid on right (peak |forces.ankle.z.right|=0.16310902304446 < threshold=0.5)

2026-07-02 15:32:37,465 - WARNING - subject_114: kinetic data flagged invalid on left (peak |forces.ankle.z.left|=0.0885322709798575 < threshold=0.5)

2026-07-02 15:32:37,466 - WARNING - subject_114: kinetic data flagged invalid on right (peak |forces.ankle.z.right|=0.1778192559887302 < threshold=0.5)

2026-07-02 15:32:37,801 - WARNING - subject_120: kinetic data flagged invalid on left (peak |forces.ankle.z.left|=0.0737692134179744 < threshold=0.5)

2026-07-02 15:32:37,802 - WARNING - subject_120: kinetic data flagged invalid on right (peak |forces.ankle.z.right|=0.0928129872563404 < threshold=0.5)

2026-07-02 15:32:38,154 - WARNING - subject_127: kinetic data flagged invalid on left (peak |forces.ankle.z.left|=0.1834186207522143 < threshold=0.5)

2026-07-02 15:32:38,155 - WARNING - subject_127: kinetic data flagged invalid on right (peak |forces.ankle.z.right|=0.229856093895199 < threshold=0.5)

2026-07-02 15:32:38,249 - WARNING - subject_129: kinetic data flagged invalid on left (peak |forces.ankle.z.left|=0.095134387056553 < threshold=0.5)

2026-07-02 15:32:38,249 - WARNING - subject_129: kinetic data flagged invalid on right (peak |forces.ankle.z.right|=0.1736095586480847 < threshold=0.5)

2026-07-02 15:32:38,343 - WARNING - subject_131: kinetic data flagged invalid on left (peak |forces.ankle.z.left|=0.0417972439929227 < threshold=0.5)

2026-07-02 15:32:38,344 - WARNING - subject_131: kinetic data flagged invalid on right (peak |forces.ankle.z.right|=0.1449237796274672 < threshold=0.5)

2026-07-02 15:32:38,677 - WARNING - subject_138: kinetic data flagged invalid on left (peak |forces.ankle.z.left|=0.150096673148051 < threshold=0.5)

2026-07-02 15:32:38,678 - WARNING - subject_138: kinetic data flagged invalid on right (peak |forces.ankle.z.right|=0.1952125473740521 < threshold=0.5)

2026-07-02 15:32:39,017 - WARNING - subject_145: kinetic data flagged invalid on left (peak |forces.ankle.z.left|=0.1565908228589033 < threshold=0.5)

2026-07-02 15:32:39,018 - WARNING - subject_145: kinetic data flagged invalid on right (peak |forces.ankle.z.right|=0.0550861259196577 < threshold=0.5)

2026-07-02 15:32:39,066 - WARNING - subject_146: kinetic data flagged invalid on left (peak |forces.ankle.z.left|=0.0693678722389312 < threshold=0.5)

2026-07-02 15:32:39,067 - WARNING - subject_146: kinetic data flagged invalid on right (peak |forces.ankle.z.right|=0.2369594775950792 < threshold=0.5)

2026-07-02 15:32:39,158 - WARNING - subject_148: kinetic data flagged invalid on left (peak |forces.ankle.z.left|=0.1390416802251714 < threshold=0.5)

2026-07-02 15:32:39,159 - WARNING - subject_148: kinetic data flagged invalid on right (peak |forces.ankle.z.right|=0.2316174558911649 < threshold=0.5)

2026-07-02 15:32:39,297 - WARNING - subject_151: kinetic data flagged invalid on left (peak |forces.ankle.z.left|=0.2999918825922582 < threshold=0.5)

2026-07-02 15:32:39,298 - WARNING - subject_151: kinetic data flagged invalid on right (peak |forces.ankle.z.right|=0.2620670854017232 < threshold=0.5)

2026-07-02 15:32:39,790 - WARNING - subject_162: kinetic data flagged invalid on left (peak |forces.ankle.z.left|=0.0880204384331503 < threshold=0.5)

2026-07-02 15:32:39,791 - WARNING - subject_162: kinetic data flagged invalid on right (peak |forces.ankle.z.right|=0.2074218289722911 < threshold=0.5)

2026-07-02 15:32:40,192 - WARNING - subject_170: kinetic data flagged invalid on left (peak |forces.ankle.z.left|=0.1723033824332814 < threshold=0.5)

2026-07-02 15:32:40,194 - WARNING - subject_170: kinetic data flagged invalid on right (peak |forces.ankle.z.right|=0.1435352446929047 < threshold=0.5)

2026-07-02 15:32:40,400 - WARNING - subject_174: kinetic data flagged invalid on left (peak |forces.ankle.z.left|=0.1202099573659142 < threshold=0.5)

2026-07-02 15:32:40,401 - WARNING - subject_174: kinetic data flagged invalid on right (peak |forces.ankle.z.right|=0.0482754755379738 < threshold=0.5)

2026-07-02 15:32:40,501 - WARNING - subject_176: kinetic data flagged invalid on left (peak |forces.ankle.z.left|=0.1339619934699385 < threshold=0.5)

2026-07-02 15:32:40,502 - WARNING - subject_176: kinetic data flagged invalid on right (peak |forces.ankle.z.right|=0.2390462511564698 < threshold=0.5)

2026-07-02 15:32:40,787 - INFO - Successfully processed data for 181 subjects.

--- Master DataFrame Preview ---

,subject_id,canonical_variable,side,0,1,2,3,4,5,6,...,42,43,44,45,46,47,48,49,50,kinetic_valid
0,subject_001,angles.pelvis.x.left,left,4.602764,4.605204,4.604534,4.605655,4.613816,4.633070,4.667278,...,5.973037,5.945259,5.889366,5.804383,5.689005,5.544058,5.368115,5.161177,4.923437,NaN
1,subject_001,angles.pelvis.x.right,right,4.065441,4.014660,3.959558,3.902478,3.846357,3.794245,3.749565,...,5.517519,5.509962,5.483638,5.441420,5.387988,5.328534,5.268434,5.213201,5.167657,NaN
2,subject_001,angles.pelvis.y.left,left,0.681206,0.856910,1.031504,1.195656,1.339530,1.456038,1.538106,...,-0.323421,-0.197632,-0.077732,0.041810,0.167911,0.306748,0.464362,0.644569,0.849063,NaN
3,subject_001,angles.pelvis.y.right,right,0.085887,0.298349,0.469021,0.598176,0.686085,0.736676,0.752406,...,-0.958634,-0.887767,-0.800937,-0.690194,-0.549976,-0.378501,-0.175731,0.052185,0.296416,NaN
4,subject_001,angles.pelvis.z.left,left,0.799303,1.006567,1.202879,1.387260,1.558564,1.716245,1.858809,...,-1.664048,-1.443630,-1.209548,-0.963032,-0.704247,-0.433457,-0.149615,0.147939,0.459754,NaN

In [3]:
# ===================================================================
# 📊 3. ANALYSIS AND REPORTING
# ===================================================================
# Generate summary tables from the processed data.
# ===================================================================
if not master_df.empty:
    logging.info("--- Starting Analysis and Reporting ---")
    generate_coverage_report(master_df, OUTPUT_DIR)
    normative_stats = calculate_normative_stats(master_df, OUTPUT_DIR)
    calculate_spatiotemporal_stats(spatiotemporal_df, OUTPUT_DIR)
    generate_kinetic_qc_report(kinetic_qc_records, OUTPUT_DIR)
else:
    logging.warning("Master DataFrame is empty. Skipping analysis.")

2026-07-02 15:32:40,805 - INFO - --- Starting Analysis and Reporting ---

2026-07-02 15:32:40,805 - INFO - Calculating variable coverage...

2026-07-02 15:32:40,811 - INFO - Coverage report saved to output\tables\coverage_by_variable.csv

==================================================
      Top 15 Variables with HIGHEST Coverage
==================================================

             canonical_variable  subject_count  coverage_pct
0           angles.ankle.x.left            181         100.0
1          angles.ankle.x.right            181         100.0
2           angles.ankle.z.left            181         100.0
3          angles.ankle.z.right            181         100.0
15           angles.hip.y.right            181         100.0
14            angles.hip.y.left            181         100.0
13           angles.hip.x.right            181         100.0
12            angles.hip.x.left            181         100.0
11  angles.footprogress.z.right            181         100.0
10   angles.footprogress.z.left            181         100.0
18           angles.knee.x.left            181         100.0
19          angles.knee.x.right            181         100.0
20           angles.knee.y.left            181         100.0
21          angles.knee.y.right            181         100.0
22           angles.knee.z.left            181         100.0

==================================================
      Top 15 Variables with LOWEST Coverage
==================================================

         canonical_variable  subject_count  coverage_pct
7      angles.elbow.y.right            172     95.027624
5      angles.elbow.x.right            172     95.027624
9      angles.elbow.z.right            172     95.027624
31  angles.shoulder.x.right            172     95.027624
37     angles.wrist.x.right            172     95.027624
39     angles.wrist.y.right            172     95.027624
35  angles.shoulder.z.right            172     95.027624
33  angles.shoulder.y.right            172     95.027624
41     angles.wrist.z.right            172     95.027624
55      forces.knee.x.right            175     96.685083
53       forces.hip.z.right            175     96.685083
54       forces.knee.x.left            175     96.685083
8       angles.elbow.z.left            175     96.685083
4       angles.elbow.x.left            175     96.685083
30   angles.shoulder.x.left            175     96.685083

2026-07-02 15:32:40,817 - INFO - Calculating normative statistics...

2026-07-02 15:32:40,867 - INFO - Normative statistics saved to output\tables\normative_stats.parquet

==================================================
      Normative Statistics Preview
==================================================

,canonical_variable,mean_0,std_0,mean_1,std_1,mean_2,std_2,mean_3,std_3,mean_4,...,mean_46,std_46,mean_47,std_47,mean_48,std_48,mean_49,std_49,mean_50,std_50
0,angles.ankle.x.left,-2.398853,4.690140,-3.835247,4.415409,-4.326124,4.285792,-3.824191,4.256961,-2.571845,...,1.958064,4.831769,1.612086,5.060435,0.925554,5.261067,-0.290040,5.354812,-1.973248,5.271002
1,angles.ankle.x.right,-1.751461,4.654969,-3.263834,4.354442,-3.817176,4.188270,-3.341426,4.121754,-2.086860,...,2.619258,5.066965,2.196473,5.207118,1.529287,5.280829,0.415397,5.220141,-1.134145,5.002163
2,angles.ankle.z.left,8.285054,22.237777,5.130843,22.345297,1.725994,22.038482,-1.323613,21.622588,-3.532209,...,4.874265,20.652747,8.621601,20.667231,10.693023,20.825684,10.955808,21.329867,9.587843,22.142414
3,angles.ankle.z.right,4.595472,20.785750,1.397302,20.869829,-2.020718,20.624582,-5.066743,20.300972,-7.253650,...,2.658123,19.615850,6.217894,19.328257,8.133409,19.294330,8.271776,19.566989,6.850842,20.063017
4,angles.elbow.x.left,31.376426,6.090145,30.797290,6.035948,30.326248,5.971206,29.981545,5.891020,29.781052,...,32.958305,5.823613,32.631743,5.885842,32.245267,5.943479,31.805771,5.995691,31.329102,6.043267

2026-07-02 15:32:40,874 - INFO - Calculating normative statistics for spatiotemporal parameters...

============================================================
      Normative Spatiotemporal Parameters Table
============================================================

,walking_speed_m_s,cadence_steps_min,stride_length_m,step_length_m,stance_time_s,swing_time_s,stance_pct
count,362.000,362.000,362.000,362.000,362.000,362.000,362.000
mean,1.024,108.451,1.130,0.553,0.689,0.427,61.626
std,0.159,10.017,0.119,0.058,0.081,0.039,2.407
min,0.663,77.720,0.860,0.383,0.530,0.305,51.456
5%,0.777,92.173,0.935,0.457,0.576,0.367,58.244
25%,0.909,101.437,1.050,0.515,0.625,0.403,60.052
50%,1.018,108.303,1.127,0.552,0.684,0.424,61.549
75%,1.138,115.942,1.201,0.586,0.741,0.451,63.058
95%,1.290,124.863,1.334,0.651,0.819,0.490,65.527
max,1.506,133.630,1.539,0.711,1.088,0.557,70.466

2026-07-02 15:32:40,886 - INFO - Spatiotemporal normative statistics saved to output\tables\spatiotemporal_normative_stats.csv

2026-07-02 15:32:40,889 - INFO - Kinetic QC report saved to output\tables\kinetic_qc_flags.csv (56/362 subject-sides flagged invalid)

==================================================
      Subjects Flagged for Invalid Kinetic Data
==================================================

      subject_id   side  kinetic_valid
2    subject_002   left          False
3    subject_002  right          False
8    subject_005   left          False
9    subject_005  right          False
16   subject_009   left          False
17   subject_009  right          False
24   subject_013   left          False
25   subject_013  right          False
42   subject_022   left          False
43   subject_022  right          False
68   subject_035   left          False
69   subject_035  right          False
82   subject_042   left          False
83   subject_042  right          False
92   subject_047   left          False
93   subject_047  right          False
124  subject_063   left          False
125  subject_063  right          False
140  subject_071   left          False
141  subject_071  right          False
158  subject_080   left          False
159  subject_080  right          False
182  subject_092   left          False
183  subject_092  right          False
192  subject_097   left          False
193  subject_097  right          False
224  subject_113   left          False
225  subject_113  right          False
226  subject_114   left          False
227  subject_114  right          False
238  subject_120   left          False
239  subject_120  right          False
252  subject_127   left          False
253  subject_127  right          False
256  subject_129   left          False
257  subject_129  right          False
260  subject_131   left          False
261  subject_131  right          False
274  subject_138   left          False
275  subject_138  right          False
288  subject_145   left          False
289  subject_145  right          False
290  subject_146   left          False
291  subject_146  right          False
294  subject_148   left          False
295  subject_148  right          False
300  subject_151   left          False
301  subject_151  right          False
322  subject_162   left          False
323  subject_162  right          False
338  subject_170   left          False
339  subject_170  right          False
346  subject_174   left          False
347  subject_174  right          False
350  subject_176   left          False
351  subject_176  right          False

In [4]:
# ===================================================================
# 📈 4. VISUALIZATION
# ===================================================================
# Create all static and interactive plots.
# ===================================================================
if not master_df.empty and 'normative_stats' in locals():
    logging.info("--- Starting Visualization ---")

    # Generate static PNGs
    png_plotter = PngPlotter(LAYOUT_CONFIG, OUTPUT_DIR)
    png_plotter.plot_all_panels(master_df, normative_stats)
    print(f"\n✅ All PNG plots saved in '{OUTPUT_DIR / 'figures'}'")

    # Generate interactive HTML reports
    html_plotter = HtmlPlotter(LAYOUT_CONFIG, OUTPUT_DIR)
    html_plotter.plot_all_panels(master_df, normative_stats)
    print(f"✅ All HTML reports saved in '{OUTPUT_DIR / 'html'}'")

    logging.info("--- ✅ Pipeline Finished Successfully! ---")
else:
    logging.warning("Master or Normative DataFrame is empty. Skipping visualization.")

2026-07-02 15:32:40,899 - INFO - --- Starting Visualization ---

2026-07-02 15:32:40,900 - INFO - Generating all PNG plot panels...

2026-07-02 15:32:40,900 - INFO - Generating PNG panel: Joint Rotation Angles...

2026-07-02 15:32:48,381 - INFO - Saved PNG panel to output\figures\joint_rotation_angles.png

2026-07-02 15:32:48,381 - INFO - Generating PNG panel: Joint Moments...

2026-07-02 15:32:51,035 - INFO - Saved PNG panel to output\figures\joint_moments.png

2026-07-02 15:32:51,035 - INFO - Generating PNG panel: Joint Powers...

2026-07-02 15:32:51,886 - INFO - Saved PNG panel to output\figures\joint_powers.png

2026-07-02 15:32:51,887 - INFO - Generating PNG panel: Joint Forces...

2026-07-02 15:32:55,663 - INFO - Saved PNG panel to output\figures\joint_forces.png

2026-07-02 15:32:55,664 - INFO - Generating PNG panel: Ground Reaction Forces...

2026-07-02 15:32:56,814 - INFO - Saved PNG panel to output\figures\ground_reaction_forces.png

2026-07-02 15:32:56,815 - INFO - Generating all HTML plot panels...

2026-07-02 15:32:56,815 - INFO - Generating HTML panel: Joint Rotation Angles...

✅ All PNG plots saved in 'output\figures'

2026-07-02 15:33:06,407 - INFO - Saved HTML panel to output\html\joint_rotation_angles.html

2026-07-02 15:33:06,408 - INFO - Generating HTML panel: Joint Moments...

2026-07-02 15:33:10,078 - INFO - Saved HTML panel to output\html\joint_moments.html

2026-07-02 15:33:10,079 - INFO - Generating HTML panel: Joint Powers...

2026-07-02 15:33:11,270 - INFO - Saved HTML panel to output\html\joint_powers.html

2026-07-02 15:33:11,270 - INFO - Generating HTML panel: Joint Forces...

2026-07-02 15:33:15,297 - INFO - Saved HTML panel to output\html\joint_forces.html

2026-07-02 15:33:15,297 - INFO - Generating HTML panel: Ground Reaction Forces...

2026-07-02 15:33:16,573 - INFO - Saved HTML panel to output\html\ground_reaction_forces.html

2026-07-02 15:33:16,574 - INFO - --- ✅ Pipeline Finished Successfully! ---

✅ All HTML reports saved in 'output\html'